import { Inter } from "next/font/google";
import "./globals.css";
import './firebase'
import Providers from "./GlobalRedux/provider";
import LogRegHeader from "./components/LogReg/LogRegHeader";


const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: "My telegram app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
		<html lang='en'>
			<body className={`${inter.className} min-h-screen`}>
				<div className="flex flex-col mx-auto max-w-[90%] pt-3">
					<Providers>
						<LogRegHeader />
						{children}
					</Providers>
				</div>
			</body>
		</html>
	)
}
