import { Inter } from 'next/font/google';
import '../globals.css';
import '../firebase';
import '../../middleware';
import AuthHeader from '../components/Auth/AuthHeader';
import Providers from '../redux/provider';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My telegram app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <div className="flex flex-col mx-auto max-w-[100%] pt-3">
          <Providers>
            <AuthHeader />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
